## echo_server_tls
##

Import('env')
Import('boostlibs')
Import('wslib')
Import('platform_libs')
Import('tls_libs')

localenv = env.Clone ()

sources = ["echo_server_tls.cpp"]

LIBS = [wslib, platform_libs, tls_libs] + boostlibs(['system',
                                                     'date_time',
                                                     'regex',
                                                     'thread'])

prg = localenv.Program('echo_server_tls', sources, LIBS = LIBS)

Return('prg')
