## echo_server
##

Import('env')
Import('boostlibs')
Import('wslib')
Import('platform_libs')

localenv = env.Clone ()

sources = ["echo_server.cpp"]

LIBS = [wslib, platform_libs] + boostlibs(['system',
                                           'date_time',
                                           'regex',
                                           'thread'])

prg = localenv.Program('echo_server', sources, LIBS = LIBS)

Return('prg')
