## sip_client
##

Import('env')
Import('boostlibs')
Import('wslib')
Import('platform_libs')

localenv = env.Clone ()

sources = ["sip_client.cpp"]

LIBS = [wslib, platform_libs] + boostlibs(['system',
                                           'date_time',
                                           'regex',
                                           'thread',
                                           'random'])

prg = localenv.Program('sip_client', sources, LIBS = LIBS)

Return('prg')
