## chat_server
##

Import('env')
Import('boostlibs')
Import('wslib')
Import('platform_libs')

localenv = env.Clone ()

sources = ["chat_server.cpp","chat.cpp"]

LIBS = [wslib, platform_libs] + boostlibs(['system',
                                           'date_time',
                                           'regex',
                                           'thread'])

prg = localenv.Program('chat_server', sources, LIBS = LIBS)

Return('prg')
