## wsperf
##

Import('env')
Import('boostlibs')
Import('wslib')
Import('platform_libs')

localenv = env.Clone ()

sources = ["wsperf.cpp",
           "request.cpp",
           "case.cpp",
           "generic.cpp",
           "stress_handler.cpp",
           "stress_aggregate.cpp",
           "wscmd.cpp"]

LIBS = [wslib] + boostlibs(['system',
                            'date_time',
                            'regex',
                            'thread',
                            'random',
                            'chrono',
                            'program_options']) + [platform_libs]

prg = localenv.Program('wsperf', sources, LIBS = LIBS)

Return('prg')
