#
#  Makefile.nt
#  
#  Copyright (C) 1998, 2009
#  Paul E. Jones <paulej@packetizer.com>
#  All Rights Reserved.
#
#############################################################################
#  $Id: Makefile.nt 13 2009-06-22 20:20:32Z paulej $
#############################################################################
#
#  Description:
#	This is a makefile for Win32 to build the programs sha, shacmp, and
#	shatest
#
#  Portability Issues:
#	Designed to work with Visual C++
#
#

.silent:

!include <win32.mak>

RM	= del /q

LIBS	= $(conlibs) setargv.obj

CFLAGS	= -D _CRT_SECURE_NO_WARNINGS /EHsc /O2 /W3

OBJS	= sha1.obj

all: sha.exe shacmp.exe shatest.exe

sha.exe: sha.obj $(OBJS)
	$(link) $(conflags) -out:$@ sha.obj $(OBJS) $(LIBS)

shacmp.exe: shacmp.obj $(OBJS)
	$(link) $(conflags) -out:$@ shacmp.obj $(OBJS) $(LIBS)

shatest.exe: shatest.obj $(OBJS)
	$(link) $(conflags) -out:$@ shatest.obj $(OBJS) $(LIBS)

.cpp.obj:
	$(cc) $(CFLAGS) $(cflags) $(cvars) $<

clean:
	$(RM) *.obj sha.exe shacmp.exe shatest.exe
