## chat_client
##

Import('env')
Import('boostlibs')
Import('wslib')
Import('platform_libs')

localenv = env.Clone ()

sources = ["chat_client.cpp","chat_client_handler.cpp"]

LIBS = [wslib, platform_libs] + boostlibs(['system',
                                           'date_time',
                                           'regex',
                                           'thread',
                                           'random'])

prg = localenv.Program('chat_client', sources, LIBS = LIBS)

Return('prg')
