## websocket++ library
##

Import('env')

localenv = env.Clone ()

sources = ["base64/base64.cpp",
           "md5/md5.c",
           "messages/data.cpp",
           "network_utilities.cpp",
           "processors/hybi_header.cpp",
           "processors/hybi_util.cpp",
           "sha1/sha1.cpp",
           "uri.cpp"]

static_lib = localenv.StaticLibrary('websocketpp', sources)
shared_lib = None # localenv.SharedLibrary('websocketpp', sources)

Return('static_lib', 'shared_lib')
